Repository destinygg/chat-gui, pull requests merged in 2022-11, with the labels that each got.

#63 /ignore and /unignore improvements
  assets/chat/js/chat.js
Labels: enhancement

#62 Add a floating user info menu
  assets/chat/css/style.scss
  assets/chat/img/icon-ban.svg
  assets/chat/img/icon-ignore.svg
  assets/chat/img/icon-logs.svg
  assets/chat/img/icon-mute.svg
  assets/chat/js/chat.js
  assets/chat/js/focus.js
  assets/chat/js/menus.js
  assets/chat/js/user.js
  assets/views/embed.html
Labels: enhancement

#60 Fix Webpack dev server
  README.md
  assets/demo.js
  webpack.config.js
Labels: bug, documentation

#74 fix: history loading after chat connect
  assets/chat/js/chat.js
Labels: bug

#71 Fixed issue with vote UI not allowing more than 9 options.
  assets/chat/css/style.scss
  assets/chat/js/vote.js
Labels: bug

#69 Added emote search. And locked higher tier emotes.
  assets/chat/css/style.scss
  assets/chat/img/icon-lock.svg
  assets/chat/js/menus/ChatEmoteMenu.js
  assets/views/embed.html
Labels: enhancement

#73 Show account creation date in user info menu
  assets/chat/js/chat.js
  assets/chat/js/menus/ChatUserInfoMenu.js
  assets/chat/js/user.js
  assets/views/embed.html
Labels: enhancement

#75 Highlight by flair.
  assets/chat/css/style.scss
  assets/chat/js/focus.js
  assets/chat/js/menus/ChatUserMenu.js
  assets/chat/js/messages/ChatUserMessage.js
Labels: enhancement
