Repository destinygg/chat-gui, pull requests merged in 2023-01, with the labels that each got.

#99 Add Rumble embed support
  assets/chat/js/chat.js
  assets/chat/js/formatters/EmbedUrlFormatter.js
Labels: enhancement

#98 Fix number at end of vote not getting included.
  assets/chat/js/vote.js
Labels: bug

#96 update ignore command to prevent users from adding themselves to their ignore list
  assets/chat/js/chat.js
Labels: bug

#101 Fix critical error on chat open when flairs can't be retrieved
  assets/chat/js/chat.js
Labels: bug

#105 Replace nanoscroller with OverlayScrollbars/some other scrolling performance improvements
  assets/chat/css/style.scss
  assets/chat/js/chat.js
  assets/chat/js/menus/ChatMenu.js
  assets/chat/js/messages/ChatEmoteMessage.js
  assets/chat/js/messages/ChatUIMessage.js
  assets/chat/js/scroll.js
  assets/chat/js/window.js
  assets/views/embed.html
  package-lock.json
  package.json
Labels: enhancement

#78 Support user-info from user-list
  assets/chat/css/style.scss
  assets/chat/img/icon-unignore.svg
  assets/chat/js/menus/ChatEmoteTooltip.js
  assets/chat/js/menus/ChatMenuFloating.js
  assets/chat/js/menus/ChatUserInfoMenu.js
  assets/chat/js/menus/ChatUserMenu.js
  assets/views/embed.html
Labels: enhancement

#109 Fix floating window background on mobile.
  assets/chat/css/style.scss
Labels: bug

#115 Subonly display
  assets/chat/css/style.scss
  assets/chat/img/icon-subonly.svg
  assets/chat/js/chat.js
  assets/views/embed.html
Labels: enhancement

#103 Show aliases in /help
  assets/chat/js/chat.js
Labels: enhancement

#104 Add pinned message support
  assets/chat/css/style.scss
  assets/chat/img/icon-unpin.svg
  assets/chat/js/chat.js
  assets/chat/js/focus.js
  assets/chat/js/messages/ChatMessage.js
  assets/chat/js/messages/MessageBuilder.js
  assets/chat/js/messages/MessageTypes.js
  assets/chat/js/messages/PinnedMessage.js
  assets/chat/js/messages/index.js
  assets/views/embed.html
  assets/views/stream.html
Labels: enhancement

#116 Timesync vote via chat server.
  assets/chat/css/style.scss
  assets/chat/js/chat.js
  assets/chat/js/poll.js
  assets/chat/js/vote.js
  assets/views/embed.html
Labels: bug, enhancement
