Repository destinygg/chat-gui, pull requests merged in 2023-04, with the labels that each got.

#193 Convert timestamp to local timezone in ban info
  assets/chat/js/chat.js
Labels: bug

#196 Keep pinned messages opaque during focus
  assets/chat/css/style.scss
Labels: bug

#197 Floating menu draggable
  assets/chat/js/menus/ChatMenuFloating.js
  assets/chat/js/menus/ChatUserInfoMenu.js
Labels: enhancement

#198 fix: pins auto-dismissing on chat reconnect
  assets/chat/js/chat.js
Labels: bug

#208 Fix on-stream chat no longer working
  assets/chat/js/menus/ChatMenuFloating.js
  assets/chat/js/menus/ChatUserInfoMenu.js
Labels: bug

#206 Poll permissions fix
  assets/chat/js/chat.js
  assets/chat/js/poll.js
Labels: bug, enhancement

#182 Sort /help
  assets/chat/js/chat.js
  assets/chat/js/commands.js
  assets/chat/js/commands.test.js
Labels: enhancement

#212 Bug fixes with setting cookie values.
  webpack.config.js
Labels: bug

#213 Max message length error message.
  assets/chat/js/chat.js
Labels: enhancement

#226 Only get user info if logged in
  assets/chat/js/chat.js
  assets/demo.js
Labels: enhancement
