Repository destinygg/chat-gui, pull requests merged in 2023-02, with the labels that each got.

#118 fix: decrease the z-index of pinned messages
  assets/chat/css/style.scss
Labels: bug

#120 Add user's tag note to user info menu.
  assets/chat/js/menus/ChatUserInfoMenu.js
  assets/views/embed.html
Labels: enhancement

#119 feat: add a "show dismissed pin" button
  assets/chat/css/style.scss
  assets/chat/img/icon-pin.svg
  assets/chat/js/chat.js
  assets/chat/js/messages/PinnedMessage.js
Labels: enhancement

#121 Display user that started poll
  assets/chat/css/style.scss
  assets/chat/js/poll.js
  assets/views/embed.html
Labels: enhancement

#123 fix: make the emote tooltip show up on right click instead
  assets/chat/js/menus/ChatEmoteTooltip.js
Labels: enhancement

#131 Fixed poll option css
  assets/chat/css/style.scss
  assets/chat/js/poll.js
Labels: bug, enhancement

#110 Fix/firefox focus
  assets/chat/js/focus.js
  assets/chat/js/messages/ChatUserMessage.js
Labels: bug

#134 fix: horizontal scrollbar appearing out of nowhere
  assets/chat/js/scroll.js
Labels: bug

#135 Pinned message design tweaks
  assets/chat/css/style.scss
Labels: enhancement

#133 Floor chat message end poll percentage.
  assets/chat/js/poll.js
Labels: bug

#141 Fixed vote command not triggering poll.
  assets/chat/js/chat.js
Labels: bug

#159 Fix issue with icons not loading
  package-lock.json
  package.json
  webpack.config.js
Labels: bug

#160 Get all tiers from emotes.
  assets/chat/js/menus/ChatEmoteMenu.js
Labels: bug

#161 Fix `/timestampformat` command
  assets/chat/js/chat.js
Labels: bug
