Repository destinygg/chat-gui, pull requests merged in 2024-11, with the labels that each got.

#539 Fix NSFW/NSFL link tagging
  assets/chat/css/messages/_base.scss
Labels: bug

#540 Fix increased visibility overriding highlighting
  assets/chat/css/messages/modifiers/_highlight.scss
  assets/chat/css/messages/modifiers/_tagged.scss
Labels: bug

#432 DES-201: add a YouTube-like event bar
  assets/chat/css/chat/_index.scss
  assets/chat/css/chat/event-bar/_event-bar-event.scss
  assets/chat/css/chat/event-bar/_index.scss
  assets/chat/css/messages/pinned/_frame.scss
  assets/chat/js/chat.js
  assets/chat/js/event-bar/EventBar.js
  assets/chat/js/event-bar/EventBarEvent.js
  assets/chat/js/focus.js
  assets/chat/js/messages/ChatDonationMessage.js
  assets/chat/js/messages/ChatEventMessage.js
  assets/chat/js/messages/MessageBuilder.js
  assets/chat/js/messages/PinnedMessage.js
  assets/chat/js/messages/subscriptions/ChatGiftedSubscriptionMessage.js
  assets/chat/js/messages/subscriptions/ChatMassSubscriptionMessage.js
  assets/chat/js/messages/subscriptions/ChatRegularSubscriptionMessage.js
  assets/chat/js/messages/subscriptions/ChatSubscriptionMessage.js
  assets/chat/js/source.js
  assets/views/embed.html
  assets/views/stream.html
  assets/views/templates.html
Labels: enhancement

#552 Allow moderators to remove events
  assets/chat/css/chat/_output.scss
  assets/chat/css/chat/event-bar/_event-bar-event.scss
  assets/chat/css/chat/event-bar/_index.scss
  assets/chat/css/menus/_event-action-menu.scss
  assets/chat/css/menus/_index.scss
  assets/chat/css/messages/event/_event.scss
  assets/chat/img/icon-ellipsis-vertical.svg
  assets/chat/js/chat.js
  assets/chat/js/const.js
  assets/chat/js/event-bar/EventBar.js
  assets/chat/js/event-bar/EventBarEvent.js
  assets/chat/js/focus.js
  assets/chat/js/menus/ChatEventActionMenu.js
  assets/chat/js/menus/index.js
  assets/chat/js/messages/ChatBroadcastMessage.js
  assets/chat/js/messages/ChatEventMessage.js
  assets/views/embed.html
  assets/views/stream.html
  assets/views/templates.html
Labels: enhancement

#550 fix: jumpy chat in firefox
  assets/chat/css/chat/_output.scss
Labels: bug

#547 Added hotkey for ESC key to scroll chat to bottom
  assets/chat/js/chat.js
  assets/chat/js/event-bar/EventBar.js
  assets/chat/js/focus.js
  assets/chat/js/window.js
Labels: enhancement

#559 Dismiss selected event by clicking it again
  assets/chat/css/chat/event-bar/_event-bar-event.scss
  assets/chat/js/event-bar/EventBar.js
Labels: enhancement

#564 Fix error when publishing new version
  .github/workflows/bump-and-release.yml
Labels: bug

#518 Move history to chat
  assets/chat/js/chat.js
  assets/chat/js/messages/ChatMessage.js
  assets/chat/js/window.js
  assets/demo.js
  package-lock.json
  package.json
Labels: enhancement

#566 Use correct lastmessage when adding a message.
  assets/chat/js/chat.js
  assets/chat/js/window.js
Labels: bug

#572 History changes and fixes
  assets/chat/js/chat.js
  assets/chat/js/messages/ChatEmoteMessage.js
  assets/chat/js/messages/MessageBuilder.js
  assets/chat/js/window.js
Labels: bug, enhancement

#575 Fix issue with duplicate messages on reconnect
  assets/chat/js/chat.js
  assets/chat/js/messages/ChatBroadcastMessage.js
  assets/chat/js/messages/ChatDonationMessage.js
  assets/chat/js/messages/ChatMessage.js
  assets/chat/js/messages/ChatUserMessage.js
Labels: bug

#513 Remove mention button from userlist
  assets/chat/css/menus/_user-list.scss
  assets/chat/img/icon-share.svg
  assets/chat/js/menus/ChatUserMenu.js
Labels: enhancement
